apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ba4uxpvqaMw=,iv:O3Wyjsclyx+WTAFBUxB7Qw75fGsqgVaYlSyBWQriats=,tag:dJsz3jPGF8yv3iG6sAzqqw==,type:str]
    user: ENC[AES256_GCM,data:Gt/3VZgH14o=,iv:lsdc860g80wnKHxdVtIKdsJ7omRkyZuXYfXaoHOoK3Q=,tag:j0GNgYb32akJ2JNxqfczzA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age12w6mrvk37jwzr6eu4w654z0qm72n8g3vsf2wkdtvxqq73chhaphqvhq0n8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMlVXVmFDenZ4Y1BScEM3
            VU5ENC9icEZrd0NvZklsekNNcGZxODRFNkZ3CjZHSlhYNWt2ODVOUjlBQjF1Y3JJ
            LzVreEZSaGpocmcybjNubk1Nc2xoNXMKLS0tIEszRkJiZCtIVDJXZDN1ZGZUTlF2
            bkpMbHBLUE9UYVAxZ3pnVWp5MnRnSmMKSbDomdGa/b+H7XpfywUZnttOejqQdgqY
            nbuyjOdSMSv4kQdlL2ehMR3Zl9CI4TdGHzdOykDBwaOjfN1qUq3gTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T12:32:43Z"
    mac: ENC[AES256_GCM,data:FaTXd2xgGlxETgKOWaCEm3+3IuE3V9Z9dVsbHGgew5A5QfU/WcdmoMTjcBZQDouhAoUnZh2m1QXLK89plS4h2+M/yNUWaYrLJ84NRn6MXFe8uUWZf7ixTToMYVHAoTcEVTI+m/cLKAkv4FT/aOZUvRH/VH/BtrsdgdN6nGK24WE=,iv:6NWWUAKi9PY4akEmNqxMOb4Bx8taqukLv4mWmj2Jt0g=,tag:fKcP4oMjQlmrmAGiT2xHKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
