apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:t2u7wtLk+WWNy81aJFwRdOFyTT/TbXd+HAIQrR7mK7uLOqy1ALRdg/UpJwAwNyzu2J0u+hnusrtbSZSXhU7DxIPKc9pZpK8Bm34gEQcqvgENTbM7KrhdMhx7ehAmwkMNZD1F0MiDiLFkgCR2NdPuuXmr6BQ9LbZDbPlmFN3Z/hKDJQxLh4HxE/5uWRehf5Swk3BMcy39glrI183PDaEUsXdxEQZ8xtYgTsyQitBUoSUf95MF+Hsyix3nEsPSSw86mgC+xEusYzpR85PMiqdrRAWcBCZlL+eJuXWB5Et1FgGSlQI3CElCCuq+oS0=,iv:PycCczLCJrblRH8ivV5Cd4Bsx9twPkV6TWyo+p7k/Hk=,tag:1/25ns3ULR9wJUVuYm9E9w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age12w6mrvk37jwzr6eu4w654z0qm72n8g3vsf2wkdtvxqq73chhaphqvhq0n8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ25kYS9mSFRLazBGOXRZ
            MWd4TnJVZ0d5UldlcklFdGRZcDUyWUE2Z1djCmRqbTB5V1dsYUVYL05Lb2tLV3B3
            QlptQjZFQjE4QVBQL1V6cHNvRVIyRFEKLS0tIHdGazl2TDRadWRsREtjM21WYTJ1
            a3lXQm04WFNZVlI5RFdxZnY1R1VWMFEKOU9IW2Frl2fXDII6WDIvaJHEYdqURq07
            X2Atrzp+2Cy53HgqX6NUVkknhPupsph3i36TU9MeCXz+X+bPDTgW6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:15:18Z"
    mac: ENC[AES256_GCM,data:dolbjqgXdoz4kNWyZTE1umF/iX1mHP/7W7HnfLDs29HPIgYI20KsufRA5/+O2JHpKnmS+iG+tfCoKmlLnXivz8BsXe8CyYqDf9Y/PeGjoeliQnadcs6lhipxl2MAuxP5WQgU+24vruPSb3db/GRce+UF73eekO2/6N0Ht8PYoD4=,iv:woUCgwcsLf1GePqOtoAk01I8dbd4VgbSN2QYGLHxoHA=,tag:pD4Ouw3NocQ4eRXWi91haA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
