apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:5pKtC4jlXR60Zm1YKIET4+2Lg4GVWKhs/vlQOcXDTtJRV44bNIIt/REvmKTtk5gg5fESSQsvRVxpUabFvmvqaL2cJYjfyTqq9T5XsbhPSeL4EZHG/QmIjkWFghiF8KuwriUF5k/U9Ki+Jw0SXcqN416xH/zBScaLZkJHK/G4BobOFYZeC5Y+UaKfTWD2XxPl8LOtGZmDg+1WbpTgsg4jRUhRVxqf5nSRDA6mwK3elVTLr+xw6uJp1rdtKwFO8MehHkMuyJgJgXhmCi5tqS8e6k4sW7JwdL1wmG4EBV4F84MRW3+K1s44s6Cq7eY=,iv:dvS5GjWHxe/zWuDkmBH5hM403LVFoFTVDlGHzY3ASgg=,tag:B5w+pCUXb5wzVEE0qGxe8g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age12w6mrvk37jwzr6eu4w654z0qm72n8g3vsf2wkdtvxqq73chhaphqvhq0n8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR01IWlFNN2R0bG93Z1gw
            ai8rT252WVBacVB6MitVQVZCcFUzZTNTZndnCjBqakcrOFNLOXB1OEt1SWNPT1U1
            UHhnVGpsbkJ6WG53TVBCcnNkeEhHZkEKLS0tIGpxNWVDUGUzblFpT0RrNWFCWFhE
            ampoQ1JHQldiYythcTF3UW93a2ZiazgKvALQ6ulgL927v2a0Mb9jiWDfcMeLngfi
            +gcbhcJAY0fZTe4dWgGB5bqbPJeL0k8gISLclv0FBv8bT/LkzWIypA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T12:01:37Z"
    mac: ENC[AES256_GCM,data:EAu1SZpIbMSxlKuaTjUwUhfrWLi1TjJarueHwdqRs59sNi4t/v3ekm5Lx3dGjLm8CRPjBwXdWEFfP9e7DGMifGD+g0agJY1hsBUsMqF+gjsTJwSj4/gogJtgaNb1kpF8J/9AOYJNbZ+sGgn4Pt6Gu4dDhW897sj+YQFgHEinVWg=,iv:QsxG5wfSgsDEeTo7E0H3GM00WwceXyTW8aIJd4myyRU=,tag:1XbVlUMzrQ3Bin2dRjSOzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
